import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Autogenerate the sidebar from the docs folder structure
const sidebars: SidebarsConfig = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
